[package]
name = "terable"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
tera = "1.0"
comrak = "0.21"
relatable = { path = "../relatable"}
log = "0.4.21"
env_logger = "0.11.3"
